### ISSUE TITLE
LeaderBoard not working, records.db cant be opened.

### ISSUE THREAD

**Issue by Beludia** [nwesterhausen/valheim-discordconnector#154]
Hello ! so basically the leaderboards dont work, the rest work fine !

here my leaderboard cfg :
```
[LeaderBoard.2]

Enabled = true
Leader Board Heading = LeaderBoard.2 Statistic Leader Board
Leader Board Time Range = AllTime
Sending Period = 600
Type = Descending
Number of Rankings = 3
Death Statistics = true
Session Statistics = false
Shout Statistics = false
Ping Statistics = false
Time Online Statistics = false
```
I tried to open records.db with LiteDB Viewer 4 but it say :

Datafile is note a LiteDB database.

The mod also record first death and work as intented so I guess the db file is not corrupted...

all collect and send stats are on true, if you have any idea, thanks !

**Comment by nwesterhausen** [comment]
What does the leaderboard say when it gets sent?

Do the server logs have any warnings/errors from DiscordConnector?

Its concerning that you are unable to use the LibeDB Studio to look at the records.db file, as it must be valid like you indicate (not sending first messages all the time).

**Comment by Beludia** [comment]
I only have the active players being sent, the others leaderboards are not.
here is the only DiscordConnector lines from my out.log : 

```
[Info   :   BepInEx] Loading [Valheim Discord Connector 2.1.3]
Fallback handler could not load library /cygdrive/c/servers/109.239.155.17/ng21427/Valheim-BepInEx/valheim_server_Data/Mono/q�(tU/mono/aot-cache/amd64/DiscordConnector.dll.so
Fallback handler could not load library /cygdrive/c/servers/109.239.155.17/ng21427/Valheim-BepInEx/valheim_server_Data/Mono/q�(tU/mono/aot-cache/amd64/DiscordConnector.dll.so
Fallback handler could not load library /cygdrive/c/servers/109.239.155.17/ng21427/Valheim-BepInEx/valheim_server_Data/Mono/q�(tU/mono/aot-cache/amd64/LiteDB.dll.so
Fallback handler could not load library /cygdrive/c/servers/109.239.155.17/ng21427/Valheim-BepInEx/valheim_server_Data/Mono/q�(tU/mono/aot-cache/amd64/LiteDB.dll.so
[Info   :Valheim Discord Connector] File watcher loaded and watching for changes to configs.
[Info   :Valheim Discord Connector] Enabling LeaderBoard.1 timer with interval 1:1800000 ms
[Info   :Valheim Discord Connector] Enabling LeaderBoard.2 timer with interval 1:36000000 ms
```
So I guess its an error with LiteDB.dll ?

**Comment by nwesterhausen** [comment]
So it says leaderboard1 is scheduled for 30m intervals and 2 is scheduled for (default) 10h intervals.

I'm not sure the Fallback handler not loading something is an issue because discord connector seems to be working, and if the player activity seems accurate then the database and litedb.dll is also working.

I'm trying to replicate this issue but when I attempt on my machine the leaderboards are getting sent.  Here is a build that includes extra debug level logging regarding the leaderboards which might give some indicators if something is not working: [DiscordConnector.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10237022/DiscordConnector.zip)

Do you mind sharing the `config-dump.json` file from the configuration folder for Discord Connector? It would confirm that the configs it is reading match what you expect. Here is the ones I was using for my testing (renamed to config-dump.txt to upload here)

[config-dump.txt](https://github.com/nwesterhausen/valheim-discordconnector/files/10237055/config-dump.txt)

**Comment by Beludia** [comment]
I used the debug version of the plugins but the logs dont seem to be different (excepte version is now 2.1.6).

configs dump sent !
[config-dump.txt](https://github.com/nwesterhausen/valheim-discordconnector/files/10237184/config-dump.txt)

**Comment by andras1984** [comment]
Similar issue here, I had my dedicated server running on a windows machine, and the leaderboard(s) were posting successfully to our discord channel, I moved hosting to Gportal, (same config, same world, etc. etc.) and now only the Active Players are being sent.

**Comment by nwesterhausen** [comment]
Is it possible for either of you to change your BepInEx logging level to include 'debug' and watch the log when a leaderboard should be sent? Active players should not work unless the records.db has records in it, and functions, so seeing logs in your environment from discord connector would be key. 

If its easier I have uploaded here a version of discord connector with the leaderboard logging set to INFO so that it can be easily seen. (Honestly I should have done this before for @Beludia but it just now occurred to me to do). 

[DiscordConnector-2.1.7-extra-logging.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10303680/DiscordConnector.zip)

**Comment by jn84** [comment]
I'm also having this issue.

I'm currently using [DiscordConnector-2.1.7-extra-logging.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10303680/DiscordConnector.zip) to try and debug. 

I currently have the leaderboards set to post every 5 minutes for debugging purposes.

Note that in both of the following cases:
- Active Players stats post normally to the discord channel and appear work correctly.
- Leaderboards do NOT post to the discord channel. I have not seen one leaderboard message in the channel since I began using this mod about two weeks ago.

---

On machine 1 (The machine that normally hosts the dedicated server) the only console output that I see is:
```
[Info   :   BepInEx] Loading [Valheim Discord Connector 2.1.7]
[Info   :Valheim Discord Connector] File watcher loaded and watching for changes to configs.
[Info   :Valheim Discord Connector] Enabling LeaderBoard.1 timer with interval 00h:05m
[Info   :Valheim Discord Connector] Enabling LeaderBoard.2 timer with interval 00h:05m
[Info   :Valheim Discord Connector] Enabling Player Activity announcement with interval 06h:00m
```

There is no further BepInEx console output regarding Discord Connector.

---

 On machine 2, I made an exact copy of the server folder from machine 1. The output is identical to machine 1, with the addition of the following console output every five minutes.

```
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for All Time Deaths composition.
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for Player Activity composition.
```
---

Again, in both cases, no leaderboards are posted to the discord channel.
[config-dump.txt](https://github.com/nwesterhausen/valheim-discordconnector/files/10309966/config-dump.txt)

**Comment by nwesterhausen** [comment]
Is machine 1 the one not posting leaderboards? Is machine 2 correctly posting? What OS are both running?

**Comment by jn84** [comment]
Correct. Apologies, see my edit. 

Machine 1 runs Windows Server 2019 
Machine 2 runs Windows 11 22622.575

In short, both machines exhibit the same behavior. I believe the difference in behavior is due to console application differences.

**Comment by nwesterhausen** [comment]
Here is another version of 2.1.7 with database methods themselves set to log at INFO level. Should indicate what totals its even gathering or if its not finding the records its looking for.

[DiscordConnector-217-deeper-logging.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10310031/DiscordConnector.zip)

**Comment by jn84** [comment]
Here is the output using [DiscordConnector-217-deeper-logging.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10310031/DiscordConnector.zip).

```
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for All Time Deaths composition.
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for Player Activity composition.
[Info   :Valheim Discord Connector] CountAllRecordsGrouped 3 records returned
[Info   :Valheim Discord Connector] Prepared to send leaderboard for 1 values
[Info   :Valheim Discord Connector] Death: Player-3: 14,Player-1: 18,Player-2: 23,
[Info   :Valheim Discord Connector] CountAllRecordsGrouped 4 records returned
[Info   :Valheim Discord Connector]  as Player-1 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-2 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-4 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-3 has 0 joins, 0
[Info   :Valheim Discord Connector] Prepared to send leaderboard for 2 values
[Info   :Valheim Discord Connector] Session: Player-1: 44,Player-2: 26,Player-3: 21,Player-4: 1,
[Info   :Valheim Discord Connector] TimeOnline: Player-3: 0,Player-4: 0,Player-2: 0,Player-1: 0,
```

**Comment by nwesterhausen** [comment]
according to that, it did gather information about the death rankings but then you never get the message on discord. so that makes sense because it can do the active time correctly.. 

Here is a version of 2.1.7 with the logging for the discord API calls and the "make leaderboard" dumping what its sending to discord as INFO logs.

[DiscordConnector-217-discord-logging.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10310103/DiscordConnector.zip)

**Comment by jn84** [comment]
Using both version you posted (pre-edit and post-edit) produce the same exact results as my last comment. There is no additional output in the console.

**Comment by nwesterhausen** [comment]
Interesting. Here is one with some logging put within the scheduled task that's supposed to run

[DiscordConnector-timer-logs.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10310188/DiscordConnector.zip)

**Comment by jn84** [comment]
Please note the edit of my last comment if you hadn't noticed it.

For [DiscordConnector-timer-logs.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10310188/DiscordConnector.zip):

```
[Info   :Valheim Discord Connector] This was sent before calling SendLeaderBoard on some leaderboard
[Info   :Valheim Discord Connector] This was sent before calling SendLeaderBoard on some leaderboard
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for All Time Deaths composition.
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for Player Activity composition.
[Info   :Valheim Discord Connector] CountAllRecordsGrouped 3 records returned
[Info   :Valheim Discord Connector] Prepared to send leaderboard for 1 values
[Info   :Valheim Discord Connector] Death: Player-3: 14,Player-1: 18,Player-2: 23,
[Info   :Valheim Discord Connector] CountAllRecordsGrouped 4 records returned
[Info   :Valheim Discord Connector]  as Player-1 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-2 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-4 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-3 has 0 joins, 0
[Info   :Valheim Discord Connector] Prepared to send leaderboard for 2 values
[Info   :Valheim Discord Connector] Session: Player-1: 44,Player-2: 26,Player-3: 21,Player-4: 1,
[Info   :Valheim Discord Connector] TimeOnline: Player-3: 0,Player-4: 0,Player-2: 0,Player-1: 0,
```

Essentially the same output with two additional lines at the beginning.

**Comment by nwesterhausen** [comment]
Based on what I can see, it's almost like it's just giving up before finishing the assembly of what it sends to discord, since we don't see messages from later in the method for that but we see the first ones. Here's another version with some extra INFO logging plugged into that method:

[DiscordConnector-info-pepper.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10310252/DiscordConnector.zip)

**Comment by jn84** [comment]
Output using [DiscordConnector-info-pepper.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10310252/DiscordConnector.zip).

```
[Info   :Valheim Discord Connector] This was sent before calling SendLeaderBoard on some leaderboard
[Info   :Valheim Discord Connector] This was sent before calling SendLeaderBoard on some leaderboard
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for All Time Deaths composition.
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for Player Activity composition.
[Info   :Valheim Discord Connector] Using AllRankings to get rankings
[Info   :Valheim Discord Connector] Using AllRankings to get rankings
[Info   :Valheim Discord Connector] CountAllRecordsGrouped 3 records returned
[Info   :Valheim Discord Connector] CountAllRecordsGrouped 4 records returned
[Info   :Valheim Discord Connector] Prepared to send leaderboard for 1 values
[Info   :Valheim Discord Connector] Death: Player-3: 14,Player-1: 18,Player-2: 23,
[Info   :Valheim Discord Connector] Turning ranking dictionary into fields for discord.
[Info   :Valheim Discord Connector] 1: Player-3: 14
2: Player-1: 18
3: Player-2: 23

[Info   :Valheim Discord Connector]  as Player-1 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-2 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-4 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-3 has 0 joins, 0
[Info   :Valheim Discord Connector] Prepared to send leaderboard for 2 values
[Info   :Valheim Discord Connector] Session: Player-1: 44,Player-2: 26,Player-3: 21,Player-4: 1,
[Info   :Valheim Discord Connector] TimeOnline: Player-3: 0,Player-4: 0,Player-2: 0,Player-1: 0,
[Info   :Valheim Discord Connector] Turning ranking dictionary into fields for discord.
```

**Comment by nwesterhausen** [comment]
We should see a log message directly after "Turning ranking dictionary..." and the printed out rankings that says "The data field appended have..." and we don't. I'm going to re-write that portion to try to get it working.

**Comment by jn84** [comment]
Output [DiscordConnector-tuple-printing.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10310310/DiscordConnector.zip):

```
[Info   :Valheim Discord Connector] This was sent before calling SendLeaderBoard on some leaderboard
[Info   :Valheim Discord Connector] This was sent before calling SendLeaderBoard on some leaderboard
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for All Time Deaths composition.
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for Player Activity composition.
[Info   :Valheim Discord Connector] Using AllRankings to get rankings
[Info   :Valheim Discord Connector] Using AllRankings to get rankings
[Info   :Valheim Discord Connector] CountAllRecordsGrouped 3 records returned
[Info   :Valheim Discord Connector] CountAllRecordsGrouped 4 records returned
[Info   :Valheim Discord Connector] Prepared to send leaderboard for 1 values
[Info   :Valheim Discord Connector] Death: Player-3: 14,Player-1: 18,Player-2: 23,
[Info   :Valheim Discord Connector] Turning ranking dictionary into fields for discord.
[Info   :Valheim Discord Connector] 1: Player-3: 14
2: Player-1: 18
3: Player-2: 23

[Info   :Valheim Discord Connector] Creating TUPLE for field list
[Info   :Valheim Discord Connector] Adding 'deaths' tuple to field list
[Info   :Valheim Discord Connector]  as Player-1 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-2 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-4 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-3 has 0 joins, 0
[Info   :Valheim Discord Connector] Prepared to send leaderboard for 2 values
[Info   :Valheim Discord Connector] Session: Player-1: 44,Player-2: 26,Player-3: 21,Player-4: 1,
[Info   :Valheim Discord Connector] TimeOnline: Player-3: 0,Player-4: 0,Player-2: 0,Player-1: 0,
[Info   :Valheim Discord Connector] Turning ranking dictionary into fields for discord.
```

**Comment by nwesterhausen** [comment]
At this point I'm out of fun names. But 
[DiscordConnector-pre-tuple-log.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10310321/DiscordConnector.zip)

**Comment by jn84** [comment]
Gotta love debugging mysterious bugs :)

Using pre-tuple-log:

```
[Info   :Valheim Discord Connector] This was sent before calling SendLeaderBoard on some leaderboard
[Info   :Valheim Discord Connector] This was sent before calling SendLeaderBoard on some leaderboard
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for All Time Deaths composition.
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for Player Activity composition.
[Info   :Valheim Discord Connector] Using AllRankings to get rankings
[Info   :Valheim Discord Connector] Using AllRankings to get rankings
[Info   :Valheim Discord Connector] CountAllRecordsGrouped 3 records returned
[Info   :Valheim Discord Connector] CountAllRecordsGrouped 4 records returned
[Info   :Valheim Discord Connector] Prepared to send leaderboard for 1 values
[Info   :Valheim Discord Connector] Death: Player-3: 14,Player-1: 18,Player-2: 23,
[Info   :Valheim Discord Connector] Turning ranking dictionary into fields for discord.
[Info   :Valheim Discord Connector] Counting Death statistics to add..
[Info   :Valheim Discord Connector] 1: Player-3: 14
2: Player-1: 18
3: Player-2: 23

[Info   :Valheim Discord Connector] Creating TUPLE for field list
[Info   :Valheim Discord Connector] Adding 'deaths' tuple to field list
[Info   :Valheim Discord Connector]  as Player-1 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-2 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-4 has 0 joins, 0
[Info   :Valheim Discord Connector]  as Player-3 has 0 joins, 0
[Info   :Valheim Discord Connector] Prepared to send leaderboard for 2 values
[Info   :Valheim Discord Connector] Session: Player-1: 44,Player-2: 26,Player-3: 21,Player-4: 1,
[Info   :Valheim Discord Connector] TimeOnline: Player-3: 0,Player-4: 0,Player-2: 0,Player-1: 0,
[Info   :Valheim Discord Connector] Turning ranking dictionary into fields for discord.
```

The only change I see is:
```
[Info   :Valheim Discord Connector] Counting Death statistics to add..
```

**Comment by nwesterhausen** [comment]
Yeah that happens right before it makes the string which has the rankings.

Here's one where it prints the length of added fields after each time it adds. But it also is confirming that stuff is not null before doing stuff (logically, I didn't think it would be null because I initialize them all)

[DiscordConnector-must-not-null.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10310382/DiscordConnector.zip)

**Comment by jn84** [comment]
Got distracted trying to get it to build from source

Output of must-not-null:

```
[Info   :Valheim Discord Connector] This was sent before calling SendLeaderBoard on some leaderboard
[Info   :Valheim Discord Connector] This was sent before calling SendLeaderBoard on some leaderboard
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for Player Activity composition.
[Info   :Valheim Discord Connector] Gathering all pertinent rankings for All Time Deaths composition.
[Info   :Valheim Discord Connector] Using AllRankings to get rankings
[Info   :Valheim Discord Connector] Using AllRankings to get rankings
[Info   :Valheim Discord Connector] CountAllRecordsGrouped 3 records returned
[Info   :Valheim Discord Connector] CountAllRecordsGrouped 4 records returned
[Info   :Valheim Discord Connector] Prepared to send leaderboard for 1 values
[Info   :Valheim Discord Connector] Death: Player-3: 14,Player-1: 18,Player-2: 23,
[Info   :Valheim Discord Connector] Turning ranking dictionary into fields for discord.
[Info   :Valheim Discord Connector] Counting Death statistics to add..
[Info   :Valheim Discord Connector] 1: Player-3: 14
2: Player-1: 18
3: Player-2: 23

[Info   :Valheim Discord Connector] Creating TUPLE for field list
[Info   :Valheim Discord Connector] Adding 'deaths' tuple to field list
[Info   :Valheim Discord Connector] (postDeath) The data fields appended have 1 length.
[Info   :Valheim Discord Connector] (allTimeOnline)  as Player-1 has 0 joins, 0
[Info   :Valheim Discord Connector] (allTimeOnline)  as Player-2 has 0 joins, 0
[Info   :Valheim Discord Connector] (allTimeOnline)  as Player-4 has 0 joins, 0
[Info   :Valheim Discord Connector] (allTimeOnline)  as Player-3 has 0 joins, 0
[Info   :Valheim Discord Connector] Prepared to send leaderboard for 2 values
[Info   :Valheim Discord Connector] Session: Player-1: 44,Player-2: 26,Player-3: 21,Player-4: 1,
[Info   :Valheim Discord Connector] TimeOnline: Player-3: 0,Player-4: 0,Player-2: 0,Player-1: 0,
[Info   :Valheim Discord Connector] Turning ranking dictionary into fields for discord.
```

**Comment by nwesterhausen** [comment]
Here's the publicized dlls and stuff you need to build. Just unzip this and point the GamePath property to the unzipped folder. [0.212.9.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10310467/0.212.9.zip)

Here's a version of the mod where I "properly" look for keys in the dictionary. 
[DiscordConnector.zip](https://github.com/nwesterhausen/valheim-discordconnector/files/10310472/DiscordConnector.zip)

**Comment by jn84** [comment]
proper did the trick!

Stats posted to discord perfectly.

I assume you killed off the debugging logs, since there's no additional console output.

---

As an aside, I still couldn't get it to build, either by adding the assemblies manually or by changing GamePath to the zipped libs you posted. In both cases, it persists with missing definitions from GamePatches and ZNetPatches. Oh well :)

**Comment by nwesterhausen** [comment]
Thanks for helping me figure out what was going on! I will publish this as 2.1.8 soon.

------

Building it was a bit of a pain, not sure what exactly changed but if I build from main it doesn't work but building from dev does. 😖 Should be resolved after 2.1.8 gets tagged

**Comment by jn84** [comment]
Glad to help :smile:

**Comment by nwesterhausen** [comment]
2.1.8 is released.
