### ISSUE TITLE
[BUG] The output for our current game includes stats from a previous world/game

### ISSUE THREAD

**Issue by n1b5** [nwesterhausen/valheim-discordconnector#240]
**Describe the issue**
We set up a new world at the same address as the old world/game and it's still pulling some stats from old player names (but same SteamID) and amalgamating them into one character's stats on the output to Discord

**Expected behavior**
Just to display the current game stats from the time we began the new world and game.

**Configuration**
Upload the `config-dump.json` file from the Discord Connector config folder.

**Screenshots**

**Server Environment**
DatHost.  Dedicated server.

**Installed Mods**
![image](https://github.com/nwesterhausen/valheim-discordconnector/assets/13946044/62d06bed-2a38-4386-9a1f-9682edc84e25)

**Additional context**
[config-dump (1).json](https://github.com/nwesterhausen/valheim-discordconnector/files/14232886/config-dump.1.json)

**Comment by nwesterhausen** [comment]
I wonder if you just copied configuration over? All the records are stored in the `records.db` file which is saved in the Discord Connector config directory. So if that file was not deleted before starting the new world, it will still have those pre-existing records.

To remove the old ones, you can use the [lite-db studio](https://github.com/mbdavid/LiteDB.Studio) app and open up the records.db file after shutting down the server and go into each table and remove the old records (everything should have a field for when it was created I think).

The other option is to delete the records.db and let it start recording records again. To ensure proper deletion, it should be delete while the server is not running (while the server is running, it will still end up with old cached records when the server stops, due to how the database works, which is a type of flush on quit while active records are in a temp file/memory).

**Comment by n1b5** [comment]
That may be the case; thank you.  I'll do as you say and report back if that's helpful for you.
