### ISSUE TITLE
Pass @'s to discord in a way that can be used to trigger discord tags

### ISSUE THREAD

**Issue by azegoca** [nwesterhausen/valheim-discordconnector#252]
I would like to have the ability to use @here or @<role|user> in-game shout to trigger that tag in discord. I think if this is possible, there would also need to be an enable boolean of the feature, and maybe even an ACL for allow/deny roles, to protect from spam/annoyance.

**Comment by nwesterhausen** [comment]
So as it is right now, any correctly formatted `@role_id`, `@user_id` or `@here` will be tagged correctly on discord. The issue is it is based on the id of the user or role and not the name of either. See [allowed-mentions object](https://discord.com/developers/docs/resources/channel#allowed-mentions-object) which is empty by default (and allows any).

Regarding the `@here` spam, it would be easy to add a toggle in the DiscordConnector configuration to specifically disallow `@here`. 

For tagging a specific role or user, the easiest way might be using one of the custom %VARN% variables since an ID can be long and ugly, that way your messages can include a mention with a varaible inclusion instead of the mention syntax: `VAR_1=<@102309592>` then `JOIN_MESSAGE=%PLAYER_NAME% joined! %VAR1` (an example which isn't formatted correctly, but gets the point across).

For players to be able to tag specific roles or users on their own by name we would have to have a dictionary of some kind to transform the message.. A bit more complicated.

**Comment by nwesterhausen** [comment]
Yes that matches my understanding but I haven’t had a chance to test it yet

**Comment by nwesterhausen** [comment]
I did test by grabbing my username, using the <@xxxx> number and when that gets sent via the webhook, it gets parsed into a mention:
![image](https://github.com/nwesterhausen/valheim-discordconnector/assets/2317381/df3d963e-4b44-4cf8-988d-4c341c566363)

With a role, using the <@&xxxx> number also gets the same:
![image](https://github.com/nwesterhausen/valheim-discordconnector/assets/2317381/96746f56-032c-45c0-bd5d-77535a52fff7)

What also works (because no restrictions are put in place by default):
![image](https://github.com/nwesterhausen/valheim-discordconnector/assets/2317381/da3e76ce-d8fe-4fc3-843b-b31c59663696)
