### ISSUE TITLE
Feature Request -Unique players & active players board

### ISSUE THREAD

**Issue by CruxCraft** [nwesterhausen/valheim-discordconnector#37]
A board that posts periodically the number of unique players on the ever server, how many have been active that day (maybe week & month too?), And how many are online right now

_Example:_

**SERVER PLAYERS**
**Online now:** 4
**Today:** 8
**Week:** 29
**Month:** 31
**Total Unique:** 42
**Most at once:** 17

**Comment by nwesterhausen** [comment]
After much time.. finally have this feature added and will be coming in release 2.1.0. 

It uses the config setting "How to discern players in Record Retrieval" to determine how to count players, and gives totals for the current day, past 7 days and all time. Counting concurrent users is a bit complicated and I don't have a good database of data to use to test with to implement it atm.

Example message:
```
Active Players
Online now: 1
Players today: 2
This week: 2
All time: 0
```

Currently all values can be enabled/disabled and it has its own timer.

Also coming in 2.1.0 is a big change to the leader boards -- instead of only having the options I created, its all user-configurable within the limitations of what is recorded. Up to 5 leader boards can be customized each with their own announcement periods, statistics displayed, ascending/descending order, number of players listed and title.
