### ISSUE TITLE
Leaderboard interval is half what it should be

### ISSUE THREAD

**Issue by thedefside** [nwesterhausen/valheim-discordconnector#99]
I have the leaderboard interval set to 600, but it's showing every 5 hours. Seems to be due to this change in Plugin.cs:

```
// leaderboardTimer.Interval = 60 * 1000 * StaticConfig.StatsAnnouncementPeriod;
leaderboardTimer.Interval = 30 * 1000 * StaticConfig.StatsAnnouncementPeriod;
```

Not sure if that was intentional or you were just debugging.

**Comment by CruxCraft** [comment]
Thanks for reporting that =] I kept meaning to get in here with the same issue but you provided a quick and dirty fix.... Now I see I can just double my interval in the meantime...

I was rebooting my server so many times yesterday I couldn't test it proper to make sure it just wasn't my bad memory...

Hoping we're eventually able to switch the intervals to cron schedule expressions so that the leader-boards aren't based off of server start time & gives more flexibility like being able to just to on certain days...
